//auth checker
export const AUTH_CHECK = "AUTH_CHECK";


//login
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_REQUEST_SUCCESS = "AUTH_REQUEST_SUCCESS";
export const AUTH_REQUEST_FAILURE = "AUTH_REQUEST_FAILURE";


//logout
export const AUTH_LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST";
export const AUTH_LOGOUT_REQUEST_SUCCESS = "AUTH_LOGOUT_REQUEST_SUCCESS";
export const AUTH_LOGOUT_REQUEST_FAILURE = "AUTH_LOGOUT_REQUEST_FAILURE";


//getItems
export const ITEM_GET_REQUEST = "ITEM_GET_REQUEST";

//addItem
export const ITEM_ADD_REQUEST = "ITEM_ADD_REQUEST";

//updateItem
export const ITEM_UPDATE_REQUEST = "ITEM_UPDATE_REQUEST";

//deleteItem
export const ITEM_DELETE_REQUEST = "ITEM_DELETE_REQUEST";


export const ITEM_REQUEST_SUCCESS = "ITEM_REQUEST_SUCCESS";
export const ITEM_REQUEST_FAILURE = "ITEM_REQUEST_FAILURE";